# permissions for end users to view dooes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: doo-viewer-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - dooes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - dooes/status
  verbs:
  - get
