# permissions for end users to edit dooes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: doo-editor-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - dooes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - dooes/status
  verbs:
  - get
